routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\ClassRoomController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserTestController;
use App\Http\Controllers\Admin\QuestionTypeController;
use App\Http\Controllers\Admin\UserDetailController;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::group(['as' => 'auth.', 'middleware' => 'auth_logged'], function () {
        Route::get('/login', [AuthController::class, 'formLogin'])->name('login.form');
        Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
    });
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
        Route::get('/profile', [AuthController::class, 'profile'])->name('user.profile');

        // user
        Route::resource('user', UserController::class);
        Route::resource('question', QuestionController::class);
        Route::resource('class-room', ClassRoomController::class)->names('class_room');
        Route::resource('test', TestController::class);
        Route::resource('user-test', UserTestController::class)->names('user_test');
        Route::resource('question-type', QuestionTypeController::class)->names('question_type');

        Route::group(['prefix' => 'user-detail', 'as' => 'user_detail.'], function (){
            Route::post('/', [UserDetailController::class, 'store'])->name('store');
            Route::put('/update/{user_detail}', [UserDetailController::class, 'update'])->name('update');
        });
    });
});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'question_type_id',
        'status',
        'note',
        'avatar',
        'images'
    ];

    public function questionType()
    {
         return $this->belongsTo(QuestionType::class, 'question_type_id', 'id');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class, 'question_id', 'id');
    }
}

app/Models/QuestionType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class QuestionType extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'status'
    ];
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\QuestionRequest;
use App\Services\QuestionService;
use App\Services\QuestionTypeService;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    protected $questionService;

    protected $questionTypeService;

    public function __construct(QuestionService $questionService, QuestionTypeService $questionTypeService)
    {
        $this->questionService = $questionService;
        $this->questionTypeService = $questionTypeService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $questions = $this->questionService->list($request->all());
        $questionTypes = $this->questionTypeService->getItemActive()->pluck('title', 'id');
        return view('pages.admin.question.index', ['questions' => $questions, 'questionTypes' => $questionTypes]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $questionTypes = $this->questionTypeService->getItemActive()->pluck('title', 'id');
        return view('pages.admin.question.create',['questionTypes' => $questionTypes]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(QuestionRequest $request)
    {
        $result = $this->questionService->create($request->all());
        return $result
            ? redirect()->route('admin.question.index')->with(['type' => 'success', 'message' => trans('question.result_action.create_success')])
            : redirect()->back()->with(['type' => 'error', 'message' => trans('question.result_action.create_fail')]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $question = $this->questionService->getById($id);
        $questionTypes = $this->questionTypeService->getItemActive()->pluck('title', 'id');
        return view('pages.admin.question.edit',['questionTypes' => $questionTypes, 'question' => $question]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(QuestionRequest $request, string $id)
    {
        $result = $this->questionService->updateById($request->all(), $id);
        return $result
            ? redirect()->route('admin.question.index')->with(['type' => 'success', 'message' => trans('question.result_action.update_success')])
            : redirect()->back()->with(['type' => 'error', 'message' => trans('question.result_action.update_fail')]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $result = $this->questionService->delete($id);
        return $result
            ? redirect()->route('admin.question.index')->with(['type' => 'success', 'message' => trans('question.result_action.delete_success')])
            : redirect()->back()->with(['type' => 'error', 'message' => trans('question.result_action.delete_fail')]);
    }
}

resources/views/pages/admin/question/create.blade.php
@extends('layouts.main.main_full')
@section('title', trans('question.page.create'))
@push("css")
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@endpush
@section('main-content')
    <div class="row">
        <div class="col-12">
            <form action="{{ route('admin.question.store') }}" method="post">
                @csrf
                <x-card type="primary">
                    <x-slot name="body" class="p-5">
                        <x-forms.input label="{{ trans('question.title.label') }}" required name="title" placeholder="{{ trans('question.title.placeholder') }}"/>
                        <x-forms.selectbox
                                label="{{ trans('question.question_type.label') }}"
                                required
                                name="question_type_id"
                                :dataSelect="$questionTypes"
                                class="input-form"
                                style="width: 100%"
                                textDefault="{{ trans('question.question_type.text_default') }}"
                        />
                        <x-forms.checkbox_switch label="{{ trans('question.status.label') }}" name="status" textOff="{{ trans('question.status.value.off') }}" textOn="{{ trans('question.status.value.on') }}"/>
                        <x-forms.textarea label="{{ trans('question.note.label') }}" name="note" placeholder="{{ trans('question.note.placeholder') }}"/>
                        <x-card type="default">
                            <x-slot name="header" class="p-4">
                                <h3 class="card-title">Answer Box</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </x-slot>
                            <x-slot name="body" class="p-4">
                                <div id="wrapper-answer">
                                    @forelse(old('answers', []) as $key => $value)
                                        @include('pages.admin.question.includes.form_answer', [
                                            'index' => $key,
                                            'valueInput' => $value['answer'],
                                            'valueCheckbox' => isset($value['status']) ? \App\Enums\AnswerStatus::Correct : \App\Enums\AnswerStatus::Wrong,
                                            'answerId' => ''
                                        ])
                                    @empty
                                        @include('pages.admin.question.includes.form_answer', [
                                            'index' => 0,
                                            'valueInput' => '',
                                            'valueCheckbox' => '',
                                            'answerId' => ''
                                        ])
                                    @endforelse
                                    @error('answers')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <x-forms.button class="btn-info add-answer">
                                    <i class='fas fa-plus'></i>
                                </x-forms.button>
                            </x-slot>
                        </x-card>
                    </x-slot>
                    <x-slot name="footer" class="px-5 text-center">
                        <x-forms.button isLink class="btn btn-default mr-4" :link="route('admin.question.index')" name="{{ trans('common.btn.back') }}"/>
                        <x-forms.button type="submit" class="btn-primary" name="{{ trans('common.btn.create') }}"/>
                    </x-slot>
                </x-card>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('js/question_answer.js') }}"></script>
    <script>
        $("input[data-bootstrap-switch]").each(function(){
            $(this).bootstrapSwitch('state', $(this).prop('checked'));
        })
    //    question answer

    </script>
@endpush

resources/views/pages/admin/question/edit.blade.php
@extends('layouts.main.main_full')
@section('title', trans('question.page.edit'))
@push("css")
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@endpush
@section('main-content')
    <div class="row">
        <div class="col-12">
            <form action="{{ route('admin.question.update', $question->id) }}" method="post">
                @csrf
                @method('put')
                <x-card type="primary">
                    <x-slot name="body" class="p-5">
                        <x-forms.input label="{{ trans('question.title.label') }}" required name="title" placeholder="{{ trans('question.title.placeholder') }}" :valueDefault="$question->title"/>
                        <x-forms.selectbox
                                label="{{ trans('question.question_type.label') }}"
                                required
                                name="question_type_id"
                                :dataSelect="$questionTypes"
                                class="input-form"
                                style="width: 100%"
                                textDefault="{{ trans('question.question_type.text_default') }}"
                                :valueDefault="$question->question_type_id"
                        />
                        <x-forms.checkbox_switch label="{{ trans('question.status.label') }}" name="status" textOff="{{ trans('question.status.value.off') }}" textOn="{{ trans('question.status.value.on') }}" :valueDefault="$question->status"/>
                        <x-forms.textarea label="{{ trans('question.note.label') }}" name="note" placeholder="{{ trans('question.note.placeholder') }}" :valueDefault="$question->note"/>
                        <x-card type="default">
                            <x-slot name="header" class="p-4">
                                <h3 class="card-title">Answer Box</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </x-slot>
                            <x-slot name="body" class="p-4">
                                <div id="wrapper-answer">
                                    @forelse(old('answers', $question->answers) as $key => $value)
                                        @php
                                            $valueCheckbox = isset($value['status']) ? ($value['status'] == 'on' ? \App\Enums\AnswerStatus::Correct : $value['status']) : App\Enums\AnswerStatus::Wrong
                                        @endphp
                                        @include('pages.admin.question.includes.form_answer', [
                                            'index' => $key,
                                            'valueInput' => $value['answer'],
                                            'valueCheckbox' => $valueCheckbox,
                                            'answerId' => $value->id ?? ''
                                        ])
                                    @empty
                                        @include('pages.admin.question.includes.form_answer', [
                                            'index' => 0,
                                            'valueInput' => '',
                                            'valueCheckbox' => '',
                                            'answerId' => ''
                                        ])
                                    @endforelse
                                    @error('answers')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <x-forms.button class="btn-info add-answer">
                                    <i class='fas fa-plus'></i>
                                </x-forms.button>
                            </x-slot>
                        </x-card>
                    </x-slot>
                    <x-slot name="footer" class="px-5 text-center">
                        <x-forms.button isLink class="btn btn-default mr-4" :link="route('admin.question.index')" name="{{ trans('common.btn.back') }}"/>
                        <x-forms.button type="submit" class="btn-primary" name="{{ trans('common.btn.create') }}"/>
                    </x-slot>
                </x-card>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('js/question_answer.js') }}"></script>
    <script>
        $("input[data-bootstrap-switch]").each(function(){
            $(this).bootstrapSwitch('state', $(this).prop('checked'));
        })
        //    question answer

    </script>
@endpush

resources/views/pages/admin/question/index.blade.php
@extends('layouts.main.main_full')
@section('title', trans('question.page.list'))
@push('css')
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
    <link rel="stylesheet" href="{{ asset('css/table.css') }}">
@endpush

@section('main-content')
    <div class="row">
        <div class="col-12">
            <form action="{{ route('admin.question.index') }}" class="form-search">
                <x-forms.input
                        name="title"
                        label="{{ trans('question.title.label') }}"
                        placeholder="{{ trans('question.title.placeholder') }}"
                        wrapperFormInput="search-input"
                        wrapperInput="wrapper-input-search"
                        wrapperLabel="wrapper-label-search"
                        :valueDefault="request()->title"
                />
                <x-forms.selectbox
                        label="{{ trans('question.question_type.label') }}"
                        name="question_type_id"
                        wrapperFormInput="search-question-type ml-4"
                        wrapperInput="wrapper-input-question-type-search"
                        wrapperLabel="wrapper-label-question-type-search"
                        :dataSelect="$questionTypes"
                        textDefault="{{ trans('question.question_type.text_default') }}"
                        :valueDefault="request()->question_type_id"
                />
                <x-forms.selectbox
                        label="{{ trans('question.status.label') }}"
                        name="status"
                        wrapperFormInput="search-input ml-4"
                        wrapperInput="wrapper-input-search"
                        wrapperLabel="wrapper-label-search"
                        :dataSelect="config('constants.question.status')"
                        textDefault="{{ trans('question.status.text_default') }}"
                        :valueDefault="request()->status"
                />
                <x-forms.button type="submit" class="btn-info ml-4" name="{{ trans('common.btn.search') }}"/>
            </form>
            <div class="card">
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{{ trans('question.title.label') }}</th>
                            <th>{{ trans('question.question_type.label') }}</th>
                            <th>{{ trans('question.status.label') }}</th>
                            <th colspan="2" class="text-center">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($questions as $index => $question)
                            <tr>
                                <td>{{ $question->id }}</td>
                                <td>{{ $question->title }}</td>
                                <td>{{ $question->questionType->title }}</div></td>
                                <td>
                                    <div @class([
                                                "p-2 badge",
                                                "badge-success" => $question->status,
                                                "badge-warning"=> !$question->status
                                            ])>
                                        {{ config('constants.question.status.' . $question->status) }}
                                    </div>
                                </td>
                                <td><a class="btn btn-warning" href="{{ route('admin.question.edit', $question->id) }}"><i class="fa-solid fa-pen-to-square"></i></a></td>
                                <td>
                                    <div type="button" class="btn btn-dark delete-item" data-toggle="modal" data-url="{{ route('admin.question.destroy', $question->id) }}" data-target="#modalDelete">
                                        <i class="fa-solid fa-trash"></i>
                                    </div>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="9" class="text-center">{{ trans('common.no_data') }}</td>
                            </tr>

                        @endforelse
                        </tbody>
                    </table>
                    {{ $questions->links('layouts.pagination.index')}}
                </div>
            </div>
        </div>
    </div>
@endsection