routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\ClassRoomController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserTestController;
use App\Http\Controllers\Admin\QuestionTypeController;
use App\Http\Controllers\Admin\UserDetailController;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::group(['as' => 'auth.', 'middleware' => 'auth_logged'], function () {
        Route::get('/login', [AuthController::class, 'formLogin'])->name('login.form');
        Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
    });
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
        Route::get('/profile', [AuthController::class, 'profile'])->name('user.profile');

        // user
        Route::resource('user', UserController::class);
        Route::resource('question', QuestionController::class);
        Route::resource('class-room', ClassRoomController::class)->names('class_room');
        Route::resource('test', TestController::class);
        Route::resource('user-test', UserTestController::class)->names('user_test');
        Route::resource('question-type', QuestionTypeController::class)->names('question_type');

        Route::group(['prefix' => 'user-detail', 'as' => 'user_detail.'], function (){
            Route::post('/', [UserDetailController::class, 'store'])->name('store');
            Route::put('/update/{user_detail}', [UserDetailController::class, 'update'])->name('update');
        });
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Enums\UserRole;
use App\Enums\UserStatus;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'full_name',
        'email',
        'password',
        'email_verified_at',
        'remember_token',
        'address',
        'phone',
        'status',
        'role',
        'birthday',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function child()
    {
        return $this->belongsToMany(User::class, 'parent_users', 'parent_id', 'user_id');
    }

    public function parent()
    {
        return $this->belongsToMany(User::class, 'parent_users', 'user_id', 'parent_id');
    }

    public function parentUsers()
    {
        return $this->hasMany(ParentUser::class, 'parent_id', 'id');
    }

    public function userDetails()
    {
        return $this->hasMany(UserDetail::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use App\Services\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected $userService;

    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $users = $this->userService->list($request->all());
        return view('pages.admin.user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $listChildren = $this->userService->getListChildren();
        return view('pages.admin.user.create', ['listChildren' => $listChildren]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(UserRequest $request)
    {
        $result = $this->userService->create($request->except('_token'));
        return $result
            ? redirect()->route('admin.user.index')->with(['type' => 'success', 'message' => trans('user.result_action.create_success')])
            : redirect()->back()->with(['type' => 'error', 'message' => trans('user.result_action.create_fail')]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        list($user, $classroom) = $this->userService->showInfo($id);
        return view('pages.admin.user.show', ['user' => $user, 'classroom' => $classroom]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $listChildren = $this->userService->getListChildren($id);
        $user = $this->userService->getUser($id);
        return view('pages.admin.user.edit', ['user' => $user, 'listChildren' => $listChildren]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UserRequest $request, $id)
    {
        $this->userService->updateUser($request->except('_token'), $id);
        return redirect()->route('admin.user.index')->with(['type' => 'success', 'message' => trans('user.result_action.update_success')]);;
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $result = $this->userService->delete($id);
        return $result
            ? redirect()->back()->with(['type' => 'success', 'message' => trans('user.result_action.delete_success')])
            : redirect()->back()->with(['type' => 'error', 'message' => trans('user.result_action.delete_fail')]);
    }
}

resources/views/pages/admin/user/create.blade.php
@extends('layouts.main.main_full')
@section('title', trans('user.page.create'))
@push("css")
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@endpush
@section('main-content')
    <div class="row">
        <div class="col-12">
            <form action="{{ route('admin.user.store') }}" method="post">
                @csrf
                <x-card type="primary">
                    <x-slot name="body" class="p-5">
                        <x-forms.input label="{{ trans('user.full_name.label') }}" name="full_name" placeholder="{{ trans('user.full_name.placeholder') }}" required/>
                        <x-forms.input label="{{ trans('user.email.label') }}" name="email" placeholder="{{ trans('user.email.placeholder') }}" required/>
                        <x-forms.input label="{{ trans('user.address.label') }}" name="address" placeholder="{{ trans('user.address.placeholder') }}" required/>
                        <x-forms.input label="{{ trans('user.phone.label') }}" name="phone" placeholder="{{ trans('user.phone.placeholder') }}" required/>
                        <x-forms.checkbox_switch class="role-user" label="{{ trans('user.role.label') }}" name="role" required textOff="{{ trans('user.role.value.off') }}" textOn="{{ trans('user.role.value.on') }}"/>
                        <x-forms.checkbox_switch label="{{ trans('user.status.label') }}" name="status" required textOff="{{ trans('user.status.value.off') }}" textOn="{{ trans('user.status.value.on') }}"/>
                        <x-forms.selectbox
                            label="{{ trans('user.user.label') }}"
                            required
                            name="users"
                            :dataSelect="$listChildren"
                            class="input-form select-parent"
                            wrapperFormInput="parent-user {{ old('role') ? '' : 'd-none' }}"
                            style="width: 100%"
                            multiple="multiple"
                            id="parent-user"
                        />
                    </x-slot>
                    <x-slot name="footer" class="px-5 text-center">
                        <x-forms.button isLink class="btn btn-default mr-4" :link="route('admin.user.index')" name="{{ trans('common.btn.back') }}"/>
                        <x-forms.button type="submit" class="btn-primary" name="{{ trans('common.btn.create') }}"/>
                    </x-slot>
                </x-card>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $("input[data-bootstrap-switch]").each(function(){
            $(this).bootstrapSwitch('state', $(this).prop('checked'));
        })
        $('.role-user').on('switchChange.bootstrapSwitch', function (event, state) {
            if (state) {
                $('.parent-user').removeClass('d-none');
            } else {
                $('.parent-user').addClass('d-none');
                $('#parent-user').select2('val', 'All');
            }
        });
    </script>
@endpush

resources/views/pages/admin/user/edit.blade.php
@extends('layouts.main.main_full')
@section('title', trans('user.page.edit'))
@push("css")
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@endpush
@section('main-content')
    <div class="row">
        <div class="col-12">
            <form action="{{ route('admin.user.update', $user['id']) }}" method="post">
                @method('put')
                @csrf
                <x-card type="primary">
                    <x-slot name="body" class="p-5">
                        <x-forms.input label="{{ trans('user.full_name.label') }}" name="full_name" placeholder="{{ trans('user.full_name.placeholder') }}" required :valueDefault="$user['full_name']"/>
                        <x-forms.input label="{{ trans('user.email.label') }}" name="email" placeholder="{{ trans('user.email.placeholder') }}" required :valueDefault="$user['email']"/>
                        <x-forms.input label="{{ trans('user.address.label') }}" name="address" placeholder="{{ trans('user.address.placeholder') }}" required :valueDefault="$user['address']"/>
                        <x-forms.input label="{{ trans('user.phone.label') }}" name="phone" placeholder="{{ trans('user.phone.placeholder') }}" required :valueDefault="$user['phone']"/>
                        <x-forms.checkbox_switch class="role-user" label="{{ trans('user.role.label') }}" name="role" required textOff="{{ trans('user.role.value.off') }}" textOn="{{ trans('user.role.value.on') }}" :valueDefault="$user['role'] == 2"/>
                        <x-forms.checkbox_switch label="{{ trans('user.status.label') }}" name="status" required textOff="{{ trans('user.status.value.off') }}" textOn="{{ trans('user.status.value.on') }}" :valueDefault="$user['status']"/>
                        <x-forms.selectbox
                                label="{{ trans('user.user.label') }}"
                                required
                                name="users"
                                :dataSelect="$listChildren"
                                class="input-form select-parent"
                                wrapperFormInput="parent-user {{ old('role', $user['role'] == \App\Enums\UserRole::Parent) ? '' : 'd-none' }}"
                                :valueDefault="$user['child']->toArray()"
                                style="width: 100%"
                                multiple="multiple"
                                id="parent-user"
                        />
                    </x-slot>
                    <x-slot name="footer" class="px-5 text-center">
                        <x-forms.button isLink class="btn btn-default mr-4" :link="route('admin.user.index')" name="{{ trans('common.btn.back') }}"/>
                        <x-forms.button type="submit" class="btn-primary" name="{{ trans('common.btn.update') }}"/>
                    </x-slot>
                </x-card>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $("input[data-bootstrap-switch]").each(function(){
            $(this).bootstrapSwitch('state', $(this).prop('checked'));
        })
        $('.role-user').on('switchChange.bootstrapSwitch', function (event, state) {
            if (state) {
                $('.parent-user').removeClass('d-none');
            } else {
                $('.parent-user').addClass('d-none');
                $('#parent-user').select2('val', 'All');
            }
        });
    </script>
@endpush

resources/views/pages/admin/user/index.blade.php
@extends('layouts.main.main_full')
@section('title', trans('user.page.list'))
@push('css')
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@endpush

@section('main-content')
    <div class="row">
        <div class="col-12">
            <form action="{{ route('admin.user.index') }}" class="form-search">
                <x-forms.input
                    name="name"
                    label="{{ trans('user.full_name.label') }}"
                    wrapperFormInput="search-input"
                    wrapperInput="wrapper-input-search"
                    wrapperLabel="wrapper-label-search"
                    :valueDefault="request()->name"
                />
                <x-forms.selectbox
                        label="{{ trans('user.status.label') }}"
                        name="status"
                        wrapperFormInput="search-input ml-4"
                        wrapperInput="wrapper-input-search"
                        wrapperLabel="wrapper-label-search"
                        :dataSelect="config('constants.user.status')"
                        :valueDefault="request()->status"
                />
                <x-forms.selectbox
                        label="{{ trans('user.role.label') }}"
                        name="role"
                        wrapperFormInput="search-input ml-4"
                        wrapperInput="wrapper-input-search"
                        wrapperLabel="wrapper-label-search"
                        :dataSelect="config('constants.user.role')"
                        :valueDefault="request()->role"
                />
                <x-forms.button type="submit" class="btn-info ml-4" name="{{ trans('common.btn.search') }}"/>
            </form>
            <div class="card">
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{{ trans('user.full_name.label') }}</th>
                            <th>{{ trans('user.email.label') }}</th>
                            <th>{{ trans('user.address.label') }}</th>
                            <th>{{ trans('user.phone.label') }}</th>
                            <th>{{ trans('user.role.label') }}</th>
                            <th>{{ trans('user.status.label') }}</th>
                            <th colspan="3" class="text-center">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($users as $index =>  $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->full_name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->address }}</td>
                                <td>{{ $user->phone }}</td>
                                <td>
                                    <div
                                            @class([
                                                "p-2 badge",
                                                "btn badge-success" => $user->role == \App\Enums\UserRole::Parent,
                                                "badge-warning"=> $user->role == \App\Enums\UserRole::Child
                                            ])
                                        data-toggle="tooltip"
                                        title="{{ $user->child->count() ? getFullNameChild($user->child->pluck('full_name')) : '' }}">
                                        {{ config('constants.user.role.' . $user->role) }}
                                    </div>
                                </td>
                                <td>
                                    <div @class([
                                                "p-2 badge",
                                                "badge-success" => $user->status,
                                                "badge-warning"=> !$user->status
                                            ])>
                                        {{ config('constants.user.status.' . $user->status) }}
                                    </div>
                                </td>
                                <td><a class="btn btn-warning" href="{{ route('admin.user.edit', $user->id) }}"><i class="fa-solid fa-pen-to-square"></i></a></td>
                                <td><a class="btn btn-info" href="{{ route('admin.user.show', $user->id) }}"><i class="fa-solid fa-eye"></i></a></td>
                                <td>
                                    <div type="button" class="btn btn-dark delete-item" data-toggle="modal" data-url="{{ route('admin.user.destroy', $user->id) }}" data-target="#modalDelete">
                                        <i class="fa-solid fa-trash"></i>
                                    </div>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="10" class="text-center">{{ trans('common.no_data') }}</td>
                            </tr>

                        @endforelse
                        </tbody>
                    </table>
                    {{ $users->links('layouts.pagination.index')}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/admin/user/show.blade.php
@extends('layouts.main.main_full')
@section('title', trans('user.page.show'))
@push('css')
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@endpush

@section('main-content')

    <x-card type="default">
        <x-slot name="header" class="p-4">
            <h3 class="card-title">{{ trans("user.title.user_info") }}</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                </button>
            </div>
        </x-slot>
        <x-slot name="body" class="p-4">
            <div class="row">
                <x-box_item classWrapper="col-md-4 col-sm-6 col-12" bgIcon="bg-info" icon="fa-solid fa-chess-pawn" label="Full Name" :value="$user->full_name" />
                <x-box_item classWrapper="col-md-4 col-sm-6 col-12" bgIcon="bg-info" icon="far fa-envelope" label="Email" :value="$user->email" />
                <x-box_item classWrapper="col-md-4 col-sm-6 col-12" bgIcon="bg-info" icon="fa-solid fa-phone" label="Phone" :value="$user->phone" />
                <x-box_item classWrapper="col-md-4 col-sm-6 col-12" bgIcon="bg-info" icon="fa-solid fa-map-location" label="Address" :value="$user->address" />
                <x-box_item classWrapper="col-md-4 col-sm-6 col-12" bgIcon="bg-info" icon="fa-solid fa-circle-user" label="Role" :value="config('constants.user.role.' . $user->role)" />
                <x-box_item classWrapper="col-md-4 col-sm-6 col-12" bgIcon="bg-info" icon="fa-solid fa-triangle-exclamation" label="Status" :value="config('constants.user.status.' . $user->status)" />
            </div>
        </x-slot>
    </x-card>
    @if($user->role == \App\Enums\UserRole::Child)
        <x-card type="default">
            <x-slot name="header" class="p-4">
                <h3 class="card-title">{{ trans("user.title.user_detail_study") }}</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                    </button>
                </div>
            </x-slot>
            <x-slot name="body" class="p-4">
                @php
                    $isAddNew = true;
                @endphp
                @foreach($user->userDetails->sortBy('start_year') as $userDetail)
                    <x-card type="default">
                        <x-slot name="header" class="p-4">
                            <h3 class="card-title">{{ $userDetail->start_year . ' - ' . $userDetail->end_year }}</h3>
                            <div class="card-tools">
                                @if($userDetail->status)
                                    <span class="badge bg-success">{{ trans("common.tag.finish") }}</span>
                                @else
                                    <span class="badge bg-warning">{{ trans("common.tag.doing") }}</span>
                                @endif
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </x-slot>
                        <x-slot name="body" class="p-4">
                            @if($userDetail->status)
                                <x-forms.input label="{{ trans('user.classroom.label') }}" name="" readonly :valueDefault="$userDetail->classRoom->nameTeacher"/>
                                <x-forms.textarea label="{{ trans('user.description.label') }}" name="" readonly :valueDefault="$userDetail->description"/>
                                <x-forms.input label="{{ trans('user.point_average.label') }}" name="" readonly :valueDefault="$userDetail->point_average"/>
                            @else
                                @php
                                    $isAddNew = false;
                                @endphp
                                <form action="{{ route('admin.user_detail.update', $userDetail->id) }}" method="post">
                                    @csrf
                                    @method('put')
                                    <x-forms.selectbox
                                            label="{{ trans('user.classroom.label') }}"
                                            required
                                            name="class_room_id"
                                            :dataSelect="$classroom"
                                            class="input-form"
                                            style="width: 100%"
                                            textDefault="{{ trans('user.classroom.text_default') }}"
                                            :valueDefault="$userDetail->class_room_id"
                                    />
                                    <x-forms.textarea label="{{ trans('user.description.label') }}" name="description" placeholder="{{ trans('user.description.placeholder') }}" :valueDefault="$userDetail->description"/>
                                    <x-forms.input label="{{ trans('user.point_average.label') }}" name readonly :valueDefault="$userDetail->point_average ?? 0" wrapperInput="d-flex">
                                        <x-slot name="after">
                                            <x-forms.button class="btn-success ml-3">
                                                <i class='fas fa-sync-alt'></i>
                                            </x-forms.button>
                                        </x-slot>
                                    </x-forms.input>
                                    <x-forms.input label name="user_id" wrapperFormInput="d-none"="d-none" :valueDefault="$user->id" />
                                    <x-forms.button type="submit" name="submit" class="btn-success d-block mx-auto"/>
                                </form>
                            @endif
                        </x-slot>
                    </x-card>
                @endforeach
                @if($isAddNew)
                    <x-card type="default">
                        <x-slot name="header" class="p-4">
                            <h3 class="card-title">{{ getYear() . ' - ' . getYear() + 1 }}</h3>
                            <div class="card-tools">
                                <span class="badge bg-primary">{{ trans("common.tag.new") }}</span>
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </x-slot>
                        <x-slot name="body" class="p-4">
                            <form action="{{ route('admin.user_detail.store') }}" method="post">
                                @csrf
                                <x-forms.selectbox
                                        label="Class room"
                                        required
                                        name="class_room_id"
                                        :dataSelect="$classroom"
                                        class="input-form"
                                        style="width: 100%"
                                        textDefault="Fill class room"
                                />
                                <x-forms.textarea label="Description" name="description" placeholder="Fill description"/>
                                <x-forms.input label name="user_id" wrapperFormInput="d-none" :valueDefault="$user->id" />
                                <x-forms.button type="submit" name="submit" class="btn-success d-block mx-auto"/>
                            </form>
                        </x-slot>
                    </x-card>
                @endif
            </x-slot>
            <x-slot name="footer" class="p-4 text-center">
                <x-forms.button isLink class="btn btn-default mr-4" :link="route('admin.user.index')" name="{{ trans('common.btn.back') }}"/>
            </x-slot>
        </x-card>
    @elseif($user->role == \App\Enums\UserRole::Parent)
        <x-card type="default">
            <x-slot name="header" class="p-4">
                <h3 class="card-title">{{ trans("user.title.user_children") }}</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                    </button>
                </div>
            </x-slot>
            <x-slot name="body" class="p-4">
                @foreach($user->child as $child)
                    <x-card type="default">
                        <x-slot name="header" class="p-4">
                            <h3 class="card-title">{{ $child->full_name }}</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </x-slot>
                        <x-slot name="body" class="p-4">
                            @forelse($child->userDetails as $childDetail)
                                <x-card type="default">
                                    <x-slot name="header" class="p-4">
                                        <h3 class="card-title">{{ $childDetail->start_year . ' - ' . $childDetail->end_year }}</h3>
                                        <div class="card-tools">
                                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                                            </button>
                                        </div>
                                    </x-slot>
                                    <x-slot name="body" class="p-4">
                                        <x-forms.input label="{{ trans('user.classroom.label') }}" name readonly :valueDefault="$childDetail->classRoom->nameTeacher"/>
                                        <x-forms.textarea label="{{ trans('user.description.label') }}" name="" readonly :valueDefault="$childDetail->description"/>
                                        <x-forms.input label="{{ trans('user.point_average.label') }}" name readonly :valueDefault="$childDetail->point_average ?? 0"/>
                                    </x-slot>
                                </x-card>
                            @empty
                                <div>{{ trans('common.no_data') }}</div>
                            @endempty
                        </x-slot>
                    </x-card>
                @endforeach
            </x-slot>
            <x-slot name="footer" class="p-4 text-center">
                <x-forms.button isLink class="btn btn-default mr-4" :link="route('admin.user.index')" name="{{ trans('common.btn.back') }}"/>
            </x-slot>
        </x-card>
    @endif
@endsection